// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchMessages(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['KafkaService']['FetchMessages'](arg1, arg2, arg3, arg4, arg5);
}

export function FetchMeta(arg1, arg2, arg3, arg4) {
  return window['go']['main']['KafkaService']['FetchMeta'](arg1, arg2, arg3, arg4);
}

export function FetchTopics(arg1) {
  return window['go']['main']['KafkaService']['FetchTopics'](arg1);
}

export function GetTopicSettings(arg1, arg2) {
  return window['go']['main']['KafkaService']['GetTopicSettings'](arg1, arg2);
}

export function ProduceMessage(arg1, arg2) {
  return window['go']['main']['KafkaService']['ProduceMessage'](arg1, arg2);
}

export function ValidateConnection(arg1) {
  return window['go']['main']['KafkaService']['ValidateConnection'](arg1);
}
