// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sarama} from '../models';
import {main} from '../models';

export function ConsumerFetch(arg1:sarama.Consumer,arg2:string,arg3:number,arg4:number,arg5:number):Promise<Array<main.KafkaMessage>>;

export function FetchMessages(arg1:main.KafkaConfig,arg2:string,arg3:number,arg4:boolean,arg5:main.PartitionSettings):Promise<main.TopicData>;

export function FetchMeta(arg1:main.KafkaConfig,arg2:string,arg3:number):Promise<main.TopicMeta>;

export function FetchTopics(arg1:main.KafkaConfig):Promise<Array<string>>;

export function GetTopicSettings(arg1:main.KafkaConfig,arg2:string):Promise<{[key: string]: string}>;

export function ProduceMessage(arg1:main.KafkaConfig,arg2:main.ProducerMessage):Promise<string>;

export function ValidateConnection(arg1:main.KafkaConfig):Promise<string>;
